//! Comments retained with the generated Sil AST until Sil supports comment nodes.

use crate::compiler::model::{GeneratedFieldId, InteractionLocation, InteractionSource, PhysicalFieldId, ResolvedSuccessor};
use crate::compiler::syntax::node::EntryId;
use crate::compiler::syntax::{EntryDecl, EntryKind};
use crate::error::{ArgentError, Result};
use silverscript_lang::ast::{ContractAst, ExprKind, Statement};

use super::contract::ContractLowerer;
use super::names::{
    hidden_cov_id_name, hidden_input_count_name, hidden_input_idx_name, hidden_observe_cov_id_name, hidden_observed_input_idx_name,
    hidden_observed_output_idx_name, hidden_output_count_name, hidden_output_idx_name,
};

/// Indices refer to nodes in `AnnotatedContractAst::contract`, not source offsets.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(in crate::compiler::codegen) enum CommentAnchor {
    Contract,
    Struct(usize),
    Fields,
    Field(usize),
    Constant(usize),
    Function(usize),
    Statement { function: usize, path: Vec<StatementStep> },
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(in crate::compiler::codegen) enum StatementStep {
    Body(usize),
    Then,
    Else,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(in crate::compiler::codegen) struct AstComment {
    pub(in crate::compiler::codegen) anchor: CommentAnchor,
    pub(in crate::compiler::codegen) text: String,
}

/// Owns the Sil AST and comment anchors in the same node order.
pub(in crate::compiler::codegen) struct AnnotatedContractAst<'src> {
    pub(in crate::compiler::codegen) contract: ContractAst<'src>,
    pub(in crate::compiler::codegen) comments: Vec<AstComment>,
}

impl AnnotatedContractAst<'_> {
    fn comment(&mut self, anchor: CommentAnchor, text: impl Into<String>) {
        self.comments.push(AstComment { anchor, text: text.into() });
    }
}

impl ContractLowerer<'_, '_> {
    /// Attach model-owned explanations to AST nodes without changing Sil output.
    pub(in crate::compiler::codegen) fn annotate_actor<'src>(
        &self,
        contract: ContractAst<'src>,
    ) -> Result<AnnotatedContractAst<'src>> {
        let mut annotated = AnnotatedContractAst { contract, comments: Vec::new() };
        annotated.comment(CommentAnchor::Contract, "Generated by argentc. Do not edit by hand.");
        if !annotated.contract.structs.is_empty() {
            annotated.comment(CommentAnchor::Struct(0), ":: state layouts");
        }

        let physical = self.model.state_lowering_by_id(self.actor_id)?.active().physical();
        if annotated.contract.fields.len() != physical.fields().len() {
            return Err(ArgentError::new(format!(
                "generated Silverscript for actor `{}` has a different number of state fields",
                self.actor.name
            )));
        }
        annotated.comment(CommentAnchor::Fields, ":: route templates");
        for (index, field) in physical.fields().iter().enumerate() {
            let label = match field.id() {
                PhysicalFieldId::Generated(GeneratedFieldId::Template(_)) => None,
                PhysicalFieldId::Generated(_) => Some(":: generated state fields"),
                PhysicalFieldId::Storage(_) => Some(":: state fields"),
            };
            let previous_label =
                index.checked_sub(1).and_then(|previous| physical.fields().get(previous)).and_then(|previous| match previous.id() {
                    PhysicalFieldId::Generated(GeneratedFieldId::Template(_)) => None,
                    PhysicalFieldId::Generated(_) => Some(":: generated state fields"),
                    PhysicalFieldId::Storage(_) => Some(":: state fields"),
                });
            if label != previous_label
                && let Some(label) = label
            {
                let label = if label == ":: state fields" { format!("{label}: {}", self.actor.name) } else { label.to_string() };
                annotated.comment(CommentAnchor::Field(index), label);
            }
        }
        if !annotated.contract.constants.is_empty() {
            annotated.comment(CommentAnchor::Constant(0), ":: constants");
        }

        let mut first_entry = true;
        for (function_index, function) in annotated.contract.functions.iter().enumerate() {
            if !function.entrypoint {
                continue;
            }
            let Some((entry_index, entry)) = self.actor.entries.iter().enumerate().find(|(_, entry)| entry.name == function.name)
            else {
                continue;
            };
            let entry_id = EntryId { actor: self.actor_id, index: entry_index };
            let entry_model = self.model.entry_model_by_id(entry_id)?;
            let mut function_comments = Vec::new();
            if first_entry {
                function_comments
                    .push(AstComment { anchor: CommentAnchor::Function(function_index), text: ":: entrypoints".to_string() });
                first_entry = false;
            }
            let shape = if entry.consumes.is_empty() { "1:N" } else { "M:N" };
            let kind = match entry.kind {
                EntryKind::Leader => format!(":: leader entry ({shape})"),
                EntryKind::Delegate => ":: delegate entry".to_string(),
            };
            function_comments.push(AstComment { anchor: CommentAnchor::Function(function_index), text: kind });

            let slot_offset = self.model.input_plan_by_id(entry_id)?.current_group_policy().slot_offset();
            let mut auth_outputs = false;
            let cov_id = hidden_cov_id_name();
            for (statement_index, statement) in function.body.iter().enumerate() {
                let anchor = CommentAnchor::Statement { function: function_index, path: vec![StatementStep::Body(statement_index)] };
                match statement {
                    Statement::VariableDefinition { name, .. } if name == &cov_id => {
                        function_comments.push(AstComment { anchor, text: ":: cov inputs".to_string() });
                    }
                    Statement::VariableDefinition { name, .. } => {
                        for input in entry_model.current().inputs() {
                            if name != &hidden_input_idx_name(input.handle()) && name != &hidden_input_count_name(input.handle()) {
                                continue;
                            }
                            if let InteractionSource::Consume(consume) = input.source() {
                                let location = match input.location() {
                                    InteractionLocation::FromStart(index) => format!("cov[{}]", slot_offset + index),
                                    InteractionLocation::FromEnd(distance) => format!("cov[-{distance}]"),
                                    InteractionLocation::Range { .. } => "covenant range".to_string(),
                                };
                                function_comments.push(AstComment {
                                    anchor: anchor.clone(),
                                    text: format!(":: input {} at {location}", consume.actor),
                                });
                            }
                        }
                        for output in entry_model.current().outputs() {
                            if name != &hidden_output_idx_name(output.handle()) && name != &hidden_output_count_name(output.handle()) {
                                continue;
                            }
                            if !auth_outputs {
                                function_comments.push(AstComment { anchor: anchor.clone(), text: ":: auth outputs".to_string() });
                                auth_outputs = true;
                            }
                            if let InteractionSource::CurrentOutput(decl) = output.source() {
                                function_comments.push(AstComment {
                                    anchor: anchor.clone(),
                                    text: format!(":: output {}: {}", output.handle(), decl.actors.join(" | ")),
                                });
                            }
                        }
                        for group in entry_model.existing_groups() {
                            let Some(observe) = group.observe() else { continue };
                            if name == &hidden_observe_cov_id_name(&observe.name) {
                                function_comments.push(AstComment {
                                    anchor: anchor.clone(),
                                    text: format!(":: observed covenant {}", observe.name),
                                });
                            }
                            for input in group.inputs() {
                                if name != &hidden_observed_input_idx_name(&observe.name, input.handle()) {
                                    continue;
                                }
                                if let InteractionSource::ObserveInput(decl) = input.source() {
                                    function_comments.push(AstComment {
                                        anchor: anchor.clone(),
                                        text: format!(":: observed input {}.{}: {}", observe.name, input.handle(), decl.actor),
                                    });
                                }
                            }
                            for output in group.outputs() {
                                if name != &hidden_observed_output_idx_name(&observe.name, output.handle()) {
                                    continue;
                                }
                                if let InteractionSource::ObserveOutput(decl) = output.source() {
                                    function_comments.push(AstComment {
                                        anchor: anchor.clone(),
                                        text: format!(":: observed output {}.{}: {}", observe.name, output.handle(), decl.actor),
                                    });
                                }
                            }
                        }
                    }
                    Statement::Require { expr, .. } => {
                        if let ExprKind::Binary { left, right, .. } = &expr.kind {
                            let left_call = matches!(&left.kind, ExprKind::Call { name, .. } if name == "OpAuthOutputCount");
                            let right_call = matches!(&right.kind, ExprKind::Call { name, .. } if name == "OpAuthOutputCount");
                            if (left_call || right_call) && !auth_outputs {
                                function_comments.push(AstComment { anchor: anchor.clone(), text: ":: auth outputs".to_string() });
                                auth_outputs = true;
                            }
                            if matches!(&left.kind, ExprKind::Call { name, .. } if name == "OpCovOutputCount") && right_call {
                                function_comments
                                    .push(AstComment { anchor, text: ":: leader authorizes all covenant continuations".to_string() });
                            }
                        }
                    }
                    _ => {}
                }
            }
            self.annotate_route_statements(&mut function_comments, &function.body, function_index, &mut Vec::new(), entry_id, entry)?;
            annotated.comments.extend(function_comments);
        }
        Ok(annotated)
    }

    /// Follow nested Sil control flow to label each authenticated successor.
    fn annotate_route_statements(
        &self,
        comments: &mut Vec<AstComment>,
        statements: &[Statement<'_>],
        function: usize,
        path: &mut Vec<StatementStep>,
        entry_id: EntryId,
        entry: &EntryDecl,
    ) -> Result<()> {
        let entry_model = self.model.entry_model_by_id(entry_id)?;
        for (index, statement) in statements.iter().enumerate() {
            path.push(StatementStep::Body(index));
            match statement {
                Statement::FunctionCall { name, args, .. } if name.starts_with("validateOutputState") => {
                    let Some(first) = args.first() else {
                        path.pop();
                        continue;
                    };
                    let route = match &first.kind {
                        ExprKind::Identifier(index_name) => {
                            entry_model.routes().iter().find(|route| index_name == &hidden_output_idx_name(&route.output))
                        }
                        ExprKind::Call { name, .. } if name == "OpAuthOutputIdx" => {
                            let [only] = entry_model.routes() else {
                                path.pop();
                                continue;
                            };
                            Some(only)
                        }
                        _ => None,
                    };
                    let anchor = CommentAnchor::Statement { function, path: path.clone() };
                    if let Some(route) = route {
                        let target = match &route.successor {
                            ResolvedSuccessor::ExactSelf => self.actor.name.clone(),
                            ResolvedSuccessor::Constructed { actor, .. } => actor.display(entry, entry_id, route.id, self.model)?,
                        };
                        comments.push(AstComment { anchor, text: format!(":: become {target}") });
                    } else if let ExprKind::Identifier(index_name) = &first.kind {
                        for group in entry_model.existing_groups() {
                            let Some(observe) = group.observe() else { continue };
                            for output in group.outputs() {
                                if index_name != &hidden_observed_output_idx_name(&observe.name, output.handle()) {
                                    continue;
                                }
                                if let InteractionSource::ObserveOutput(decl) = output.source() {
                                    comments.push(AstComment {
                                        anchor: anchor.clone(),
                                        text: format!(":: observed become {}.{} -> {}", observe.name, output.handle(), decl.actor),
                                    });
                                }
                            }
                        }
                    }
                }
                Statement::Block { body, .. } | Statement::For { body, .. } => {
                    self.annotate_route_statements(comments, body, function, path, entry_id, entry)?;
                }
                Statement::If { then_branch, else_branch, .. } => {
                    path.push(StatementStep::Then);
                    self.annotate_route_statements(comments, then_branch, function, path, entry_id, entry)?;
                    path.pop();
                    if let Some(else_branch) = else_branch {
                        path.push(StatementStep::Else);
                        self.annotate_route_statements(comments, else_branch, function, path, entry_id, entry)?;
                        path.pop();
                    }
                }
                _ => {}
            }
            path.pop();
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    use crate::compiler::loader::load_inline_program;
    use crate::compiler::model::{AppCompilationContext, default_route_planner};
    use silverscript_lang::ast::{Statement, format_contract_ast};

    use super::{CommentAnchor, ContractLowerer, StatementStep};

    #[test]
    fn comment_records_follow_the_retained_ast_without_entering_sil() {
        for (case, actor, expected) in [
            ("input_template_route_reuse", "Controller", ":: become Peer"),
            ("open_observed_actor_binding", "Cell", ":: observed become remote.agent -> observed_agent"),
        ] {
            let path = PathBuf::from("tests/fixtures/emit").join(case).join("app.ag");
            let source = std::fs::read_to_string(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(&path)).expect("fixture exists");
            let program = load_inline_program(path, source).expect("fixture resolves");
            let model = AppCompilationContext::from_resolved(&program, None, &BTreeMap::new(), &default_route_planner)
                .expect("fixture model validates");
            let lowerer = ContractLowerer::new(model.types.names[actor], &model).expect("actor lowerer exists");
            let annotated = lowerer.annotate_actor(lowerer.lower_actor().expect("contract lowers")).expect("comments attach");
            assert!(
                annotated
                    .comments
                    .iter()
                    .any(|comment| comment.anchor == CommentAnchor::Fields && comment.text == ":: route templates")
            );
            let comment = annotated.comments.iter().find(|comment| comment.text == expected).expect("route comment retained");
            let CommentAnchor::Statement { function, path } = &comment.anchor else {
                panic!("route comment must point to a statement")
            };
            let [StatementStep::Body(index)] = path.as_slice() else { panic!("route comment must point into an entry body") };
            assert!(matches!(annotated.contract.functions[*function].body[*index], Statement::FunctionCall { .. }));
            assert!(!format_contract_ast(&annotated.contract).lines().any(|line| line.trim_start().starts_with("//")));
        }
    }
}
